---
version: '2'
services:
  app-website:
    build: .
    container_name: app-multi-window
    image: oaklabs/app-multi-window:latest
    network_mode: host
    devices:
      # remove if you dont need to share your graphics card explicitely
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
